site_name: Python resources in HPC
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/bs21/
copyright: CC BY 4.0 License
repo_name: bs21
repo_url: http://github.com/efurlanm/bs21/
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: teal
        accent: teal
    font: false
    features:
        - header.autohide
plugins:
    - search
markdown_extensions:
    - def_list
    - md_in_html
    - tables
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
extra_css:
    - css/extra.css
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
exclude_docs: |
    .*
nav:
    - Abstract: index.md
    - 1. Introduction: introduction.md
    - 2. The Five-Point Stencil Test Problem: stencil.md
    - 3. F90 and Python Implementations of the Test Problem: implementation.md
    - 4. Analysis of the Parallel Performance for the Test Problem: analysis.md
    - 5. Final Remarks: remarks.md
    - 6. Acknowledgements: acknowledgements.md
    - References: references.md
