site_name: Python resources in HPC
site_author: Eduardo Furlan
copyright: CC BY 4.0 License
repo_name: bs21
repo_url: http://github.com/efurlanm/bs21/
docs_dir: docs-src
site_dir: docs
use_directory_urls: false  # need for inline html and dir navigation
theme:
    name: material
    palette:
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
        primary: teal
        accent: teal
    features:
        - header.autohide
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - def_list
    - md_in_html
    - tables
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
    - css/extra.css
exclude_docs: |
    .ipynb_checkpoints
    .git

